name: Build and Upload Deltroid
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    name: Build and upload Deltroid
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-13'
            version: '14.3.1'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --recursive --init && pod install

      - name: Install dependencies
        run: brew install ldid

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Build Deltroid
        run: |
          xcodebuild -project Delta.xcodeproj \
          -scheme Delta \
          -sdk iphoneos \
          archive -archivePath ./archive \
          CODE_SIGNING_REQUIRED=NO \
          AD_HOC_CODE_SIGNING_ALLOWED=YES \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM=XYZ0123456 \
          ORG_IDENTIFIER=com.rileytestut \
          | xcpretty && exit ${PIPESTATUS[0]}
      - name: Fakesign app
        run: |
          rm -rf archive.xcarchive/Products/Applications/Delta.app/Frameworks/DeltaCore.framework/Frameworks/
          ldid -S Delta/Resources/tempEnt.plist archive.xcarchive/Products/Applications/Delta.app/Delta
      - name: Convert to IPA
        run: |
          mkdir Payload
          mkdir Payload/Delta.app
          cp -R archive.xcarchive/Products/Applications/Delta.app/ Payload/Delta.app/
          zip -r Delta.ipa Payload
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Delta.ipa
          path: Delta.ipa
